#                                                                        #
# Settings Configuration for the Expose package                          #
#                                                                        #

TYPO3:
  TypoScript:
    # We need to Disable this, because otherwise it catches redirect Exceptions
    catchRuntimeExceptions: FALSE
  Neos:
    typoScript:
      autoInclude:
        'TYPO3.Expose': TRUE
  Flow:
    object:
      excludeClasses:
       'TYPO3.Expose' : ['Neos\\.*']