#                                                                        #
# Settings Configuration for the Expose package                          #
#                                                                        #

TYPO3:
  Expose:
    Pagination:
      Limits:
        - 10
        - 20
        - 100
        - 1000
        - 10000
      Default: 20
      MaxPages: 8

  TYPO3CR:
    contentTypes:
      'TYPO3.TYPO3:Section':
        nodeLabelGenerator: 'TYPO3\TYPO3CR\Domain\Model\EelNodeLabelGenerator'
        nodeLabelGeneratorOptions:
          expression: '"Section " + context.property("_name")'
      'TYPO3.TYPO3:Text':
        nodeLabelGenerator: 'TYPO3\TYPO3CR\Domain\Model\EelNodeLabelGenerator'
        nodeLabelGeneratorOptions:
          expression: 'strings.crop(strings.cleanup(context.property("headline") + " " + context.property("text")), 50)'
      'TYPO3.TYPO3:Html':
        nodeLabelGenerator: 'TYPO3\TYPO3CR\Domain\Model\EelNodeLabelGenerator'
        nodeLabelGeneratorOptions:
          expression: 'strings.crop(strings.cleanup(context.property("source")), 50)'
  Form:
    presets:
      expose:
        title: "Default Preset for TYPO3.Expose"
        parentPreset: 'default'
        formElementTypes:
          ### override default layout path ###
          'TYPO3.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://TYPO3.Expose/Private/Form/Layouts/{@type}.html'

          ### override template path of TYPO3.Form:Form ###
          'TYPO3.Form:Form':
            renderingOptions:
              templatePathPattern: 'resource://TYPO3.Expose/Private/Form/Form.html'

          'TYPO3.Form:SelectionMixin':
            implementationClassName: 'TYPO3\Expose\FormElements\OptionsFormElement'

          'TYPO3.Expose:PasswordWithHashing':
            superTypes: ['TYPO3.Form:PasswordWithConfirmation']
            implementationClassName: 'TYPO3\Expose\FormElements\PasswordWithHashing'


          ### FORM ELEMENTS: CONTAINER ###
          'TYPO3.Expose:Page':
            superTypes: ['TYPO3.Form:Page']

          'TYPO3.Expose:Hidden':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:TextMixin']
            implementationClassName: 'TYPO3\Expose\FormElements\ComplexFormElement'

          'TYPO3.Expose:InlineStacked':
            superTypes: ['TYPO3.Form:Section']
            implementationClassName: 'TYPO3\Expose\FormElements\InlineFormElement'
            renderingOptions:
              renderableNameInTemplate: 'inline'

          'TYPO3.Expose:InlineStackedItem':
            superTypes: ['TYPO3.Expose:InlineStacked']


          'TYPO3.Expose:InlineTabular':
            superTypes: ['TYPO3.Expose:InlineStacked']

          'TYPO3.Expose:InlineTabularItem':
            superTypes: ['TYPO3.Expose:InlineStacked']


          'TYPO3.Expose:InlineSeamless':
            superTypes: ['TYPO3.Expose:InlineStacked']

          'TYPO3.Expose:InlineSeamlessItem':
            superTypes: ['TYPO3.Expose:InlineStacked']