#                                                                        #
# Settings Configuration for the Expose package                          #
#                                                                        #

TYPO3:
  TypoScript:
    # We need to Disable this, because otherwise it catches redirect Exceptions
    catchRuntimeExceptions: FALSE