#                                                                        #
# Settings Configuration for the Expose package                          #
#                                                                        #

TYPO3:
  TypoScript:
    # We need to Disable this, because otherwise it catches redirect Exceptions
    catchRuntimeExceptions: FALSE

  Flow:
    security:
      authorization:
        accessDecisionVoters:
          TYPO3.Expose: TYPO3\Expose\Security\Voter